# NUMPY / PANDAS

In [3]:
import numpy as np
a = np.arange(15) #1차원 데이터
print(a)
a = a.reshape(3, 5)  #2차원 데이터
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
b = [-1, 2, 5, 0, -3 ]
b = np.array(b)
#array를 하는 이유는 리스트 연산 불가라, 연산이 가능한 숫자로 변형하기 위함.

t = ( 0,3,4,5,6,)
t = np.array(t)

s = {2,4,5,6,7}
s = np.array(s)
# 딕셔너리 호환은 안됨.
# set은 가능

In [13]:
print(b.shape)
print(b.ndim)
print(b.dtype)
print(np.abs(b)) #절대값
# print(np.sqrt(b)) #제곱근을 구하는 함수
print(np.sqrt(np.abs(b)))
print(np.square(b)) # 제곱
print(np.isnan(b)) # nan여부를 묻는 함수 true or false(데이터가 없는 지 있는지 확인함)
print(np.mean(b)) #평균
print(np.max(b)) #최대값
print(np.min(b)) #최소값
print(np.argmax(b)) #최대값 인덱스
print(np.argmin(b)) #최소값 인덱스
print(np.sort(b)) #정렬 오름차순
print(np.sort(b)[::1]) #정렬 내림차순
print(np.median(b)) #중앙값

(5,)
1
int32
[1 2 5 0 3]
[1.         1.41421356 2.23606798 0.         1.73205081]
[ 1  4 25  0  9]
[False False False False False]
0.6
5
-3
2
4
[-3 -1  0  2  5]
[-3 -1  0  2  5]
0.0


In [33]:
c = [ [ 1, 2, 3, ], [4, 5, 6] ] #2차원이라 대괄호 2개
print(c, type(c))
c = np.array(c)
print(type(c))
print(c)

print(np.sum(c))
print(np.sum(c, axis=0))  #행끼리
print(np.sum(c, axis=1))

print(np.mean(c))
print(np.mean(c, axis=0))

print(np.median(c))
print(np.median(c, axis=0))
print(np.median(c, axis=1))

print(np.max(c)    )  
print(np.max(c, axis=0))

#표준편차 구할 때 
print(np.std(c))
#분산 구할 때
print(np.var(c))

[[1, 2, 3], [4, 5, 6]] <class 'list'>
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
3.5
[2.5 3.5 4.5]
[2. 5.]
6
[4 5 6]
1.707825127659933
2.9166666666666665


In [49]:
# element wise
d = [10, 20, 30, 40, 50]
# print(d+2) list는 연산안됨. 그래서 np하는거임
d = np.array(d)
print(d+2)

e = np.array( [1, 2, 3, 4, 5] ) 
print(d+e)
print(d**2) #제곱 연산자
print(e**2)
print( d* np.sin(d)) #요소별로 계산도 가능함
print( d > 35 ) #비교 연산자는 논리값(숫자값이 아닌)이 나옴. 

print(np.add(d,e))
print(np.subtract(d,e))
print(np.multiply(d,e))
print(np.divide(d,e))

[12 22 32 42 52]
[11 22 33 44 55]
[ 100  400  900 1600 2500]
[ 1  4  9 16 25]
[ -5.44021111  18.25890501 -29.64094872  29.80452642 -13.11874269]
[False False False  True  True]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [59]:
f = np.array( [ [0, 1] , [1, 1] ] )
g = np.array( [ [2, 0] , [3, 4] ] )

#행렬곱을 연산한다???
print(f * g) #그냥 곱셈
print( f @ g ) #행렬곱을 구하는 것

print(np.dot(f,g)) # 행렬곱 함수
print(f.dot(g))

[[0 0]
 [3 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]


In [77]:
h = np.zeros(10)
print(h)
i = np.zeros((5, 5))
print(i)
j = np.ones(10)
print(j)

# np.random.random   0~1 사이의 난수 발생
# np.random.randint  균일 분포의 정수 난수 발생
# np.random.rand     0~1 사이의 균일 분포 난수 matrix array 생성
# np.random.randn    가우시안 표준 정규 분포 난수 matrix array 생성
# np.random.normal   평균, 표준편차, sample 개수

k = np.random.random(10)
print(type(k))

# 반복문(for) 만들어서 10개짜리 데이터 만들기
k = np.random.random(10) * 100
# list만드는 문법: k(10개짜리 데이터)를 
# i에 하나씩 넣어서 그냥 i값을 바로쓸고야~~
k = [ int(i) for i in k ] 
print(type(k))
print(k)

k = np.array( [int(i) for i in k ] )
print(type(k))
print(k)

print(np.random.randint(10, 20))
print(np.random.rand(5,2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
<class 'list'>
[4, 41, 5, 35, 13, 42, 67, 40, 37, 81]
<class 'numpy.ndarray'>
[ 4 41  5 35 13 42 67 40 37 81]
14
[[0.85518269 0.76611295]
 [0.38330836 0.34137981]
 [0.03413639 0.28965958]
 [0.98339696 0.07520937]
 [0.50097329 0.66706742]]


In [111]:
#슬라이싱
m = [ i for i in range(10, 20) ]

# [start : end -1 : space,간격 ]
print( m[0:5] )
print( m[0:5:2] )
print( m[:] )
print(m[5:])
print(m[:-1])
print(m[::-1])

# ndarray
w = np.arange(10, 20)
print( w[0:5])
print( w[0:5:2])
print(w[:-2])


[10, 11, 12, 13, 14]
[10, 12, 14]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[15, 16, 17, 18, 19]
[10, 11, 12, 13, 14, 15, 16, 17, 18]
[19, 18, 17, 16, 15, 14, 13, 12, 11, 10]
[10 11 12 13 14]
[10 12 14]
[10 11 12 13 14 15 16 17]


In [139]:
# list 값
r = [ [1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15] ]
print( r[2][2] )  #인덱스가 2번인 행에서 인덱스가 2번인 값
print(r[:][:])
print(r[2][:])
print(r[1][:2])

# 앞에도 2까지 뒤에서도 2까지
print(r[:2][:2]) #앞과 뒤가 열이라는 보장이 없음.

# print(r[:, :]) #error 리스트는 에러남.

s = np.arange(1, 16).reshape(3, 5) #1~16까지의 숫자를 3행 5열로 나타내라
print(s)
print(s[2][2])
print(s[:][:])
print(s[2][:])
print(s[1][:2])
print(s[:2][:1])     #[[2차원도 똑같다]]

print( s[:2, :2 ])
print( s[:, :])
print( s[:-1, :-1]) #[[1 2 3 4][6 7 8 9]]
print(s[2,2])
print(s[::-1, ::-1] )

print(s[[0, 2]])

13
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
[11, 12, 13, 14, 15]
[6, 7]
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
13
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[6 7]
[[1 2 3 4 5]]
[[1 2]
 [6 7]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[1 2 3 4]
 [6 7 8 9]]
13
[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [141]:
# 전치 행렬

print(s)  #3행 5열
print(s.T) #5행 3열

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [173]:
#결합 / 분리
a = [1, 2, 3]
b = [4, 5, 6]
for ab in zip(a, b):
    print(ab)
print(list(zip(a,b)))
print(a+b)    #list합칠 때 그대로 연산자 사용가능함_그냥 붙임, 계산은 안됨.
# print(a + 1) #연산은 안됨
print(a*2)

(1, 4)
(2, 5)
(3, 6)
[(1, 4), (2, 5), (3, 6)]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


In [161]:
c = np.random.rand(2,2) * 100
print (c)

[[ 0.87807282  5.03277529]
 [38.29901113 41.69566793]]


In [177]:
# 합치기
c = np.floor(np.random.rand(2,2) * 100)
print(c)
d = np.floor(np.random. rand(2,2) *100)
print(d)
print(np.hstack((c,d)))
print(np.vstack((c,d)))
print(c + 2)

[[13. 85.]
 [68. 62.]]
[[ 8. 29.]
 [97. 91.]]
[[13. 85.  8. 29.]
 [68. 62. 97. 91.]]
[[13. 85.]
 [68. 62.]
 [ 8. 29.]
 [97. 91.]]
[[15. 87.]
 [70. 64.]]


In [199]:
# 분할, 나누기
e = np.floor( np.random.rand(2, 15)* 100)
print(e)

print( np.hsplit( e, 3 ))               # 3개로 잘라라.
for arr in np.hsplit( e, 3):
    print("hsplit", arr)
for arr in np.hsplit( e, ( 3, 7 )):     # [0:3]까지, [3:7] 까지, [7:0]까지 튜플로 자를 위치를 입력함.
    print("hsplit2", arr)

[[79. 40. 65. 92. 24. 72. 70. 88. 81. 48. 27. 11. 76.  8. 31.]
 [60. 86. 63.  5. 74. 60.  1. 42. 20. 86. 60. 64.  0. 78. 18.]]
[array([[79., 40., 65., 92., 24.],
       [60., 86., 63.,  5., 74.]]), array([[72., 70., 88., 81., 48.],
       [60.,  1., 42., 20., 86.]]), array([[27., 11., 76.,  8., 31.],
       [60., 64.,  0., 78., 18.]])]
hsplit [[79. 40. 65. 92. 24.]
 [60. 86. 63.  5. 74.]]
hsplit [[72. 70. 88. 81. 48.]
 [60.  1. 42. 20. 86.]]
hsplit [[27. 11. 76.  8. 31.]
 [60. 64.  0. 78. 18.]]
hsplit2 [[79. 40. 65.]
 [60. 86. 63.]]
hsplit2 [[92. 24. 72. 70.]
 [ 5. 74. 60.  1.]]
hsplit2 [[88. 81. 48. 27. 11. 76.  8. 31.]
 [42. 20. 86. 60. 64.  0. 78. 18.]]


In [219]:
f = np.array( [ 1, 2, 3, 4, 5] )
g = np.array( [ 'A', 'B', 'C', 'D', 'E'] )
h = np.array( [ True, True, False, False, True ] )
# 삼항연산           조건? 참 : 거짓
                     # 참if 조건 else 거짓
for x, y, z in zip(f, g, h):
    print(x, y, z)

print( [x if z else y for x, y, z in zip(f, g, h) ] )

#간결한 함수 where
print(np.where(h,f,g)) # 맨 앞(h)이 조건이고 나머지가 값임.( 조건, 참일때, 거짓일때)
print( np.where( f < 3, 'small', 'big'))
print( np.where( h, 'true', 'false'))

1 A True
2 B True
3 C False
4 D False
5 E True
[1, 2, 'C', 'D', 5]
['1' '2' 'C' 'D' '5']
['small' 'small' 'big' 'big' 'big']
['true' 'true' 'false' 'false' 'true']


In [225]:
help(np.where)

Help on _ArrayFunctionDispatcher in module numpy:

where(...)
    where(condition, [x, y], /)

    Return elements chosen from `x` or `y` depending on `condition`.

    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.

    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.

    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.

    See Also
    --------
    choose
    nonzero : The function that is called when x and y are om

In [237]:
# 파일 생성하기
i = np.arange( 10 ) # 0~9
np.save( 'i.npy', i )
# 파일 빼내기
ii = np.load( 'i.npy' )
print(type(ii))

j = np.arange(10)
k = np.arange(20)
np.savez( 'jk.npz', x=j, y=k )
jk = np.load( 'jk.npz' )
print( type( jk ))
print( jk['x'] )
print( jk['y'] )

<class 'numpy.ndarray'>
<class 'numpy.lib.npyio.NpzFile'>
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
