# PANDAS
- Series - 1차원
    - 컬럼에 다른 데이터 없으면 자동으로 숫자가 입력됨
    - 1줄인 경우 왼쪽이 인덱스인데 숫자입력불가이므로 위쪽 컬럼이 자동 인덱스가 됨.
- DataFrame - 2차원 이상

In [13]:
import pandas as pd
import numpy as np

# Series - index를 따로 지정하지 않는 경우
s = pd.Series( [1, 2, 3, 4, 5, 6, 7, 8, 9] )
print( type( s ) )
print( s.index )
print( s.dtype )
print( s )

<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=9, step=1)
int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


In [17]:
# Series - index를 따로 지정하는 경우
s = pd.Series( [1, 2, 3, 4, 5, 6, 7, 8, 9] )
s.index = [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I' ]
print(s)

A    1
B    2
C    3
D    4
E    5
F    6
G    7
H    8
I    9
dtype: int64


In [31]:
s = pd.Series( [1, 2, 3, 4, 5, 6, 7, 8, 9], [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I' ] )
print(s)
print( s.index )       #index export
print( s.values )      #valuses export
# print( s[0] ) error~!~
print( s['A'] )
print(s.A)
print( s[0:5] )
print( s['A' : 'D'] )

A    1
B    2
C    3
D    4
E    5
F    6
G    7
H    8
I    9
dtype: int64
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'], dtype='object')
[1 2 3 4 5 6 7 8 9]
1
1
A    1
B    2
C    3
D    4
E    5
dtype: int64
A    1
B    2
C    3
D    4
dtype: int64


### Dictionary로 Series 만들기
(map, JSON)

In [54]:
d = { 'A':10, 'D':20, 'F':30, 'H':40 }
print(type(d))

for key, value in d.items() : #모든 key, value를 튜플로 받아서 꺼내줌.
    print( key, ":", value )


print( d['A'] )
# print( d.A )  # ERROR!!!

s = pd.Series( d )   #dictionary를 pandas로 바꾸기!(Series)
print( s.index )
print( s.values )
print( s[ 'A' ])
print( s.A )
print( s[0:3] )
print( s['A': 'F'])

<class 'dict'>
A : 10
D : 20
F : 30
H : 40
10
Index(['A', 'D', 'F', 'H'], dtype='object')
[10 20 30 40]
10
10
A    10
D    20
F    30
dtype: int64
A    10
D    20
F    30
dtype: int64


### DataFrame
- numpy.array 로 데이터를 만드는 방법도 있고!
- dictionary -> dataframe   
      * key하나에 data가 여러인 경우 생성~!

In [77]:
# key "name, age, tel" = column
d = {
    'name' : [ 'kim', 'lee', 'park', 'jung' ],
    'age' : [ 25, 30, 35, 26 ],
    'tel' : ['1111-2222', '1223-3434', '4553-4444', '2453-4566' ]
}
print( type(d) )

df = pd.DataFrame( d )
print( df )
print( df.index )
print( df.columns )
print( df.values )   #값만 꺼내면, numpy array로 만들어서 출력해 줌. 호환이 되니까. 

df.index.name = 'Num'
df.columns.name = 'User'
print( df )
print( df.index )
print( df.columns )

<class 'dict'>
   name  age        tel
0   kim   25  1111-2222
1   lee   30  1223-3434
2  park   35  4553-4444
3  jung   26  2453-4566
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'age', 'tel'], dtype='object')
[['kim' 25 '1111-2222']
 ['lee' 30 '1223-3434']
 ['park' 35 '4553-4444']
 ['jung' 26 '2453-4566']]
User  name  age        tel
Num                       
0      kim   25  1111-2222
1      lee   30  1223-3434
2     park   35  4553-4444
3     jung   26  2453-4566
RangeIndex(start=0, stop=4, step=1, name='Num')
Index(['name', 'age', 'tel'], dtype='object', name='User')


In [81]:
# numpy -> DataFrame

In [97]:
n = np.array(
    [['kim', 25, '1111-2222'],
     ['lee', 30, '1223-3434'],
     ['park', 35, '4553-4444'],
     ['jung', 26, '2453-4566']]
)
print( type(n) )
df = pd.DataFrame( n )
#column & index 바꾸는 방법
df.columns = [ 'name', 'age', 'tel' ]
df.index = [ 'A', 'B', 'C', 'D' ]

print(df)
print(df.index)
print(df.columns)

df = pd.DataFrame( n, columns = ['name','age', 'tel'], index =[ 'A', 'B', 'C', 'D' ] )
print(df)

#data를 가져왔을 때 전처리 전에 비어있는 데이터 확인하는 함수
# count: 갯수
# unique: 데이터 특징
# top: 제일 위쪽 값
# freq: 
print(df.describe())

<class 'numpy.ndarray'>
   name age        tel
A   kim  25  1111-2222
B   lee  30  1223-3434
C  park  35  4553-4444
D  jung  26  2453-4566
Index(['A', 'B', 'C', 'D'], dtype='object')
Index(['name', 'age', 'tel'], dtype='object')
   name age        tel
A   kim  25  1111-2222
B   lee  30  1223-3434
C  park  35  4553-4444
D  jung  26  2453-4566
       name age        tel
count     4   4          4
unique    4   4          4
top     kim  25  1111-2222
freq      1   1          1


In [113]:
print( df['name'] )             #열 기준 작업
print( df[['name', 'tel']] )
# print( df['name'][2] ) #'2'라는 인덱스가 없어서 경고
print( df['name'].C )
print( df['name']['B':'D'] )

A     kim
B     lee
C    park
D    jung
Name: name, dtype: object
   name        tel
A   kim  1111-2222
B   lee  1223-3434
C  park  4553-4444
D  jung  2453-4566
park
B     lee
C    park
D    jung
Name: name, dtype: object


In [115]:
print( df[:][:] )  #데이터 전체 다뽑기! 2차원 그대로

   name age        tel
A   kim  25  1111-2222
B   lee  30  1223-3434
C  park  35  4553-4444
D  jung  26  2453-4566


In [125]:
#데이터 변경, 삭제

In [123]:
# df[ 'address' ] = [ 'seoul', 'suwon', 'incheon', 'ansan' ]
# df.loc[ 'age', 'A'] = 30
# df['adult'] = df['age'].astype( np.int64 ) > 30
# print(df)

In [133]:
# 데이터 정렬하기
# Series 정렬
s = pd.Series( [ 10, 40, 50, 20, 70, 60 ] , index = ['a', 'd','f','g','b','c'] )
print( s )
s = s.sort_index()
s = s.sort_values()
print(s)

a    10
d    40
f    50
g    20
b    70
c    60
dtype: int64
a    10
g    20
d    40
f    50
c    60
b    70
dtype: int64


In [294]:
# DataFrame 정렬
df = pd.DataFrame( [[ 4, 5, 1, 2 ],
                    [300, 400, 200, 100],
                    [ 20, 10, 40, 30 ]], index=[ 'c', 'a', 'b' ], columns=['D', 'C', 'A', 'B'])
print(df)

# index & column & value
df = df.sort_index()          #index
# df = df.sort.index( axis=0 )  #행끼리 정리 axis 0,1 = 행끼리 열끼리
df = df.sort_index( axis=1, ascending=False )    #column #행을 내림차순으로

df= df.sort_values( by='A', ascending=False )   #A를 기준으로 내림차순, 행끼리

print(df)


     D    C    A    B
c    4    5    1    2
a  300  400  200  100
b   20   10   40   30
     D    C    B    A
a  300  400  100  200
b   20   10   30   40
c    4    5    2    1


In [157]:
# 슬라이싱
# .iloc
# .loc      라벨 인덱싱
# .ix       deprecated

#list
m = [ [1,2,3,], [4,5,6,], [7,8,9] ]
print(m)
print(m[2][2])
print(m[:][:])
print(m[:2][:2])

#print(m[:2, :2]) error!!!

#Numpy
n = np.array( m )
print( n )
print(n[2][2])
print(n[:][:])
print(n[:2][:2])
print(n[:2, :2])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [161]:
#pandas
df = pd.DataFrame( n )
print( df )
print( df[2][2] )

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
9


In [167]:
# iloc
df = pd.DataFrame( np.arange(1, 21).reshape( 5, 4 ), columns=['A', 'B', 'C', 'D'])
print(df)

# print(df.iloc[2][2] )

#loc
print(df)



    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20


In [189]:
df.loc[0,'A'] = 99
df.loc[1, 'A':'C'] = [100, 101, 102]
print(df)

df.loc[3, ['A','C', 'E']] = [203,344,565]

print(df)

     A    B    C
0   99    2    3
1  100  101  102
2    9   10   11
3  203   14  344
4   17   18   19
     A    B    C      E
0   99    2    3    NaN
1  100  101  102    NaN
2    9   10   11    NaN
3  203   14  344  565.0
4   17   18   19    NaN


In [193]:
# #delete

# del(df['E'])

# # drop 은 완전 데이터 제거
# # df.drop( 'F' ) #delete column //error, why-? 
# df = df.drop( 'D', axis=1 )
# df = df.drop(4)

# print(df)

In [229]:
df = pd.DataFrame(
    [['kim', 25, '1111-2222', 'seoul'],
     ['lee', 30, '1223-3434', np.nan],
     ['park', 35, '4553-4444', 'suwon'],
     ['jung', 26, '2453-4566', np.nan],
     ['cho', 33, '5454-1111', np.nan]], columns=[ 'name', 'age', 'tel', 'adrress' ]
)
print(df)

df.loc[ 5, : ] = [ np.nan, np.nan, np.nan, np.nan ]

df['income'] = [ 300, np.nan, 500, 600, np.nan, 300 ]
# df['address'].fillna(value='seoul', inplace=True)
df.fillna( {'address' : 'seoul'}, inplace=True )
df.fillna( {'income' : np.mean(df['income']) }, inplace =True)



print(df)

   name  age        tel adrress
0   kim   25  1111-2222   seoul
1   lee   30  1223-3434     NaN
2  park   35  4553-4444   suwon
3  jung   26  2453-4566     NaN
4   cho   33  5454-1111     NaN
   name   age        tel adrress  income
0   kim  25.0  1111-2222   seoul   300.0
1   lee  30.0  1223-3434     NaN   425.0
2  park  35.0  4553-4444   suwon   500.0
3  jung  26.0  2453-4566     NaN   600.0
4   cho  33.0  5454-1111     NaN   425.0
5   NaN   NaN        NaN     NaN   300.0


In [231]:
#결측치 대체
# df.loc[ 5, : ] = [ np.nan, np.nan, np.nan, np.nan ]

# df['income'] = [ 300, np.nan, 500, 600, np.nan, 300 ]
# # df['address'].fillna(value='seoul', inplace=True)
# df.fillna( {'address' : 'seoul'}, inplace=True )
# df.fillna( {'income' : np.mean(df['income']) } )


# print(df)

In [ ]:
# df[ 'address' ] = [ 'seoul', np.nan, np.nan, 'suwon', np.nan ]

# df.loc[ df['address'] == np.nan, 'address' ]


# print(df)

In [ ]:
# 결측값 제거
# drop, del
df.loc[ ::2, 'tel' ] = np.nan
print(df)

In [292]:
# pandas 함수

df = pd.DataFrame(
    [[ 'kim', 40, 56, 64 ],
     [ 'lee', 54, np.nan, 23 ],
     [ 'soo', 56, 64, 55 ],
     [ 'cho', np.nan, np.nan, 34 ],
     [ 'chang', 53, 65, 66],
    ['hong', np.nan, np.nan, np.nan]], columns = ['name', 'kor','eng','math']
)

print(df)

# print(df.count( axis=1 )) #행 갯수 세는 건데 별로 안 쓸듯..!!!

# print(df.min())
# print(df.loc[:, 'kor':'math'].min( axis=1 ))
# print(df.max())
# # print(df.mean) # 이름은 평균 못내니까 에러남
# print(df.loc[:, 'kor':'math'].mean())        #과목별 평균점수
# print(df.loc[:, 'kor':'math'].mean(axis=1))  #학생별 평균점수
# print(df.sum())
# print(df.loc[:, 'kor':'math'].sum(axis=1))

# print(df.loc[:, 'kor':'math'].median())        #중앙값


df['tot'] = df.loc[:, 'kor':'math'].sum( axis =1 )
df['avg'] = df.loc[:, 'kor':'math'].mean(axis =1 )

# 상관관계를 분석할 때
# 가설'국어를 잘하는 애는 수학도 잘한다.'을 증명하고 싶을 때
# 국어점수와 수학점수의 상관관계를 분석해야 한다.
print( df['kor'].corr(df['math']))

# 숫자가 1에 가까우면 양의 상관관계
# 숫자가 0에 가까우면 상관관계가 낮다
# 숫자가 -1에 가까우면 음의 상관관계

print(df)

    name   kor   eng  math
0    kim  40.0  56.0  64.0
1    lee  54.0   NaN  23.0
2    soo  56.0  64.0  55.0
3    cho   NaN   NaN  34.0
4  chang  53.0  65.0  66.0
5   hong   NaN   NaN   NaN
-0.40493220663933044
    name   kor   eng  math    tot        avg
0    kim  40.0  56.0  64.0  160.0  53.333333
1    lee  54.0   NaN  23.0   77.0  38.500000
2    soo  56.0  64.0  55.0  175.0  58.333333
3    cho   NaN   NaN  34.0   34.0  34.000000
4  chang  53.0  65.0  66.0  184.0  61.333333
5   hong   NaN   NaN   NaN    0.0        NaN
